const $=id=>document.getElementById(id);let ctx,guideBuffer,instrumentalBuffer,analysis=null,playing=[];
function startSeconds(){const bpm=+$('bpm').value,bpb=+$('beatsPerBar').value,bar=Math.max(1,+$('startBar').value),beat=Math.max(1,+$('startBeat').value);return (((bar-1)*bpb)+(beat-1))*(60/bpm)}
function updateStart(){$('startReadout').textContent=`Vocal entry: ${startSeconds().toFixed(3)} sec from song start — Bar ${$('startBar').value}, Beat ${$('startBeat').value}`}
['bpm','beatsPerBar','startBar','startBeat'].forEach(id=>$(id).addEventListener('input',updateStart));updateStart();
[['timing','timingVal'],['pitch','pitchVal'],['expression','expressionVal']].forEach(([a,b])=>$(a).addEventListener('input',()=>$(b).textContent=$(a).value+'%'));
async function decodeFile(input){const f=input.files[0];if(!f)return null;ctx=ctx||new AudioContext();return await ctx.decodeAudioData(await f.arrayBuffer())}
function mono(buffer){const out=new Float32Array(buffer.length);for(let c=0;c<buffer.numberOfChannels;c++){const d=buffer.getChannelData(c);for(let i=0;i<out.length;i++)out[i]+=d[i]/buffer.numberOfChannels}return out}
function analyzeGuide(buffer){const x=mono(buffer),sr=buffer.sampleRate,frame=Math.max(64,Math.floor(sr*.02)),hop=Math.max(32,Math.floor(sr*.01));let env=[],times=[];for(let i=0;i+frame<x.length;i+=hop){let s=0;for(let j=0;j<frame;j++)s+=x[i+j]*x[i+j];env.push(Math.sqrt(s/frame));times.push(i/sr)}const sorted=[...env].sort((a,b)=>a-b),med=sorted[Math.floor(sorted.length*.55)]||0,threshold=Math.max(med*2.2,.012);let onsets=[];for(let i=2;i<env.length-2;i++){if(env[i]>threshold&&env[i]>env[i-1]*1.18&&env[i]>=env[i+1]){const t=times[i];if(!onsets.length||t-onsets[onsets.length-1]>.065)onsets.push(t)}}let first=0;for(let i=0;i<env.length;i++){if(env[i]>Math.max(med*1.7,.008)){first=times[i];break}}return{duration:buffer.duration,sampleRate:sr,firstSound:first,onsets}}
function draw(buffer,a){const c=$('wave'),g=c.getContext('2d'),W=c.width,H=c.height;g.fillStyle='#0d0e11';g.fillRect(0,0,W,H);g.strokeStyle='#59606d';g.beginPath();const x=mono(buffer),step=Math.max(1,Math.floor(x.length/W));for(let px=0;px<W;px++){let mn=1,mx=-1;for(let i=px*step;i<Math.min(x.length,(px+1)*step);i++){mn=Math.min(mn,x[i]);mx=Math.max(mx,x[i])}g.moveTo(px,(1-mx)*H/2);g.lineTo(px,(1-mn)*H/2)}g.stroke();g.strokeStyle='#f0bc57';a.onsets.forEach(t=>{let xx=t/a.duration*W;g.beginPath();g.moveTo(xx,0);g.lineTo(xx,H);g.stroke()})}
$('analyze').onclick=async()=>{guideBuffer=await decodeFile($('guide'));if(!guideBuffer){alert('Load a guide vocal first.');return}analysis=analyzeGuide(guideBuffer);draw(guideBuffer,analysis);$('analysisOut').textContent=`Guide duration: ${analysis.duration.toFixed(3)} s\nFirst audible performance: ${analysis.firstSound.toFixed(3)} s\nDetected phrase/accent onsets: ${analysis.onsets.length}\nRequested song entry: ${startSeconds().toFixed(3)} s\n\nInternal timing stays relative to your guide. Only the whole performance is placed on the requested bar/beat.`;$('preview').disabled=false;$('exportAligned').disabled=false}
function stopAll(){playing.forEach(s=>{try{s.stop()}catch(e){}});playing=[]}$('stop').onclick=stopAll;
$('preview').onclick=async()=>{stopAll();ctx=ctx||new AudioContext();await ctx.resume();instrumentalBuffer=await decodeFile($('instrumental'));const now=ctx.currentTime+.08;if(instrumentalBuffer){const s=ctx.createBufferSource();s.buffer=instrumentalBuffer;s.connect(ctx.destination);s.start(now);playing.push(s)}if(guideBuffer){const s=ctx.createBufferSource();s.buffer=guideBuffer;s.connect(ctx.destination);s.start(now+startSeconds(),Math.max(0,analysis?.firstSound||0));playing.push(s)}};
function audioBufferToWav(buffer){const ch=buffer.numberOfChannels,sr=buffer.sampleRate,len=buffer.length,ab=new ArrayBuffer(44+len*ch*2),v=new DataView(ab),w=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+len*ch*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,sr,true);v.setUint32(28,sr*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,len*ch*2,true);let p=44;for(let i=0;i<len;i++)for(let c=0;c<ch;c++){let x=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([ab],{type:'audio/wav'})}
$('exportAligned').onclick=async()=>{if(!guideBuffer||!analysis)return;const off=new OfflineAudioContext(2,Math.ceil((startSeconds()+guideBuffer.duration+1)*guideBuffer.sampleRate),guideBuffer.sampleRate),s=off.createBufferSource();s.buffer=guideBuffer;s.connect(off.destination);s.start(startSeconds(),Math.max(0,analysis.firstSound));const rendered=await off.startRendering(),blob=audioBufferToWav(rendered),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aligned_guide.wav';a.click();URL.revokeObjectURL(a.href)};
$('renderAI').onclick=async()=>{const guide=$('guide').files[0],voice=$('voiceRef').files[0];if(!guide){alert('Load a guide vocal first.');return}if($('voiceMode').value==='reference'&&voice&&!$('consent').checked){alert('Confirm you have permission to use the reference voice.');return}const fd=new FormData();fd.append('guide',guide);if(voice)fd.append('voice_ref',voice);fd.append('lyrics',$('lyrics').value);fd.append('mode',$('mode').value);fd.append('start_seconds',startSeconds());$('engineStatus').textContent='Sending render request...';try{const r=await fetch('/api/render',{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ai_vocal_aligned.wav';a.click();$('engineStatus').textContent='Render complete.'}catch(e){$('engineStatus').textContent='Backend engine is not configured yet. '+e.message}}
